apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
  labels:
    app: healthcare
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: anuradhasahoo333412/healthcare
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
  labels:
    app: healthcare
spec:
  selector:
    app: healthcare

  type: NodePort
  ports:
  - nodePort: 31002
    port: 8080
    targetPort: 8080
